In [3]:
import pandas as pd

status = pd.read_csv(
    "../data/openclosenppark.csv",
    encoding="utf-8"
)

status.head()

,ลำดับ,หน่วยงาน,ชื่อหน่วยงาน,จังหวัด,ชื่อแหล่งท่องเที่ยว,latitude,longitude,เปิดตลอดปี,วันที่เริ่มปิด,วันที่สิ้นสุดการปิด,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,1.0,อุทยานแห่งชาติ,เขาใหญ่,ปราจีนบุรี,แก่งหินเพิง,14.16748,101.72896,ไม่ใช่,1-มี.ค.,30-เม.ย.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,อุทยานแห่งชาติ,เขาใหญ่,ปราจีนบุรี,น้ำตกตะคร้อ,14.18198,101.59266,ไม่ใช่,1-มี.ค.,30-เม.ย.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,อุทยานแห่งชาติ,เขาใหญ่,นครนายก,น้ำตกสาริกา,14.30885,101.25535,ไม่ใช่,1-เม.ย.,30-เม.ย.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,อุทยานแห่งชาติ,เขาใหญ่,ปราจีนบุรี,น้ำตกธารทิพย์,14.19731,101.5432,ไม่ใช่,-,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,อุทยานแห่งชาติ,เขาใหญ่,นครราชสีมา,น้ำตกผากล้วยไม้,14.43153,101.40173,ใช่,-,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
print("ขนาดข้อมูล:")
print(status.shape)

print("\nชื่อคอลัมน์:")
print(status.columns.tolist())

print("\nชนิดข้อมูล:")
print(status.dtypes)

ขนาดข้อมูล:
(1598, 26)

ชื่อคอลัมน์:
['ลำดับ', 'หน่วยงาน', 'ชื่อหน่วยงาน', 'จังหวัด', 'ชื่อแหล่งท่องเที่ยว', 'latitude', 'longitude', 'เปิดตลอดปี', 'วันที่เริ่มปิด', 'วันที่สิ้นสุดการปิด', 'สาเหตุการปิด', 'หมายเหตุ', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25']

ชนิดข้อมูล:
ลำดับ                  float64
หน่วยงาน                   str
ชื่อหน่วยงาน               str
จังหวัด                    str
ชื่อแหล่งท่องเที่ยว        str
latitude                   str
longitude                  str
เปิดตลอดปี                 str
วันที่เริ่มปิด             str
วันที่สิ้นสุดการปิด        str
สาเหตุการปิด               str
หมายเหตุ                   str
Unnamed: 12            float64
Unnamed: 13            float64
Unnamed: 14            float64
Unnamed: 15            float64
Unnamed: 16            float64
Unnamed: 17            float64
Unnamed: 18            float64
Unnamed: 19            float64
Unnamed: 20            float64
Unnamed: 21            float64
Unnamed: 22            float64
Unnamed: 23            float64
Unnamed: 24            float64
Unnamed: 25            float64
dtype: object

2. ตรวจข้อมูลที่เกี่ยวข้องกับการเปิด-ปิด

เลือกเฉพาะคอลัมน์ที่จำเป็นสำหรับการวิเคราะห์ช่วงเปิด-ปิด
รวมถึงข้อมูลจังหวัดและพิกัดสำหรับการเชื่อมข้อมูลและสร้างแผนที่

In [5]:
# ตัดคอลัมน์ Unnamed ที่ไม่จำเป็น
status = status.loc[:, ~status.columns.str.startswith("Unnamed")].copy()

# ตัดช่องว่างชื่อคอลัมน์
status.columns = status.columns.str.strip()

print("ขนาดข้อมูลหลังตัดคอลัมน์ว่าง:")
print(status.shape)

print("\nMissing Values:")
print(status.isna().sum())

print("\nค่าของคอลัมน์ 'เปิดตลอดปี':")
print(status["เปิดตลอดปี"].value_counts(dropna=False))

print("\nจำนวนหน่วยงาน:")
print(status["ชื่อหน่วยงาน"].nunique())

print("\nจำนวนแหล่งท่องเที่ยว:")
print(status["ชื่อแหล่งท่องเที่ยว"].nunique())

status[
    [
        "ชื่อหน่วยงาน",
        "จังหวัด",
        "ชื่อแหล่งท่องเที่ยว",
        "เปิดตลอดปี",
        "วันที่เริ่มปิด",
        "วันที่สิ้นสุดการปิด",
        "สาเหตุการปิด"
    ]
].head(20)

ขนาดข้อมูลหลังตัดคอลัมน์ว่าง:
(1598, 12)

Missing Values:
ลำดับ                    23
หน่วยงาน                 14
ชื่อหน่วยงาน              2
จังหวัด                  24
ชื่อแหล่งท่องเที่ยว       4
latitude                 49
longitude                49
เปิดตลอดปี                5
วันที่เริ่มปิด          815
วันที่สิ้นสุดการปิด     812
สาเหตุการปิด           1042
หมายเหตุ               1551
dtype: int64

ค่าของคอลัมน์ 'เปิดตลอดปี':
เปิดตลอดปี
ใช่       894
ไม่ใช่    699
NaN         5
Name: count, dtype: int64

จำนวนหน่วยงาน:
245

จำนวนแหล่งท่องเที่ยว:
1481

,ชื่อหน่วยงาน,จังหวัด,ชื่อแหล่งท่องเที่ยว,เปิดตลอดปี,วันที่เริ่มปิด,วันที่สิ้นสุดการปิด,สาเหตุการปิด
0,เขาใหญ่,ปราจีนบุรี,แก่งหินเพิง,ไม่ใช่,1-มี.ค.,30-เม.ย.,ช่วงเวลาดังกล่าวไม่มีน้ำและให้ทรัพยากร
1,เขาใหญ่,ปราจีนบุรี,น้ำตกตะคร้อ,ไม่ใช่,1-มี.ค.,30-เม.ย.,ธรรมชาติฟื้นตัว
2,เขาใหญ่,นครนายก,น้ำตกสาริกา,ไม่ใช่,1-เม.ย.,30-เม.ย.,ช่วงเวลาดังกล่าวไม่มีน้ำและให้ทรัพยากร
3,เขาใหญ่,ปราจีนบุรี,น้ำตกธารทิพย์,ไม่ใช่,-,-,ปิดตลอดทั้งปี
4,เขาใหญ่,นครราชสีมา,น้ำตกผากล้วยไม้,ใช่,-,-,-
5,เขาใหญ่,นครราชสีมา,น้ำตกกองแก้ว,ใช่,-,-,-
6,เขาใหญ่,นครนายก,น้ำตกเหวนรก,ใช่,-,-,-
7,เขาใหญ่,นครราชสีมา,น้ำตกเหวสุวัต,ใช่,-,-,-
8,เขาใหญ่,นครราชสีมา,หอดูสัตว์หนองผักชี,ใช่,-,-,-
9,เขาใหญ่,นครนายก,น้ำตกนางรอง,ใช่,-,-,-
10,เขาใหญ่,นครราชสีมา,หอดูสัตว์คลองปลากั้ง (ขญ4),ใช่,-,-,-
11,เขาใหญ่,นครนายก,จุดชมทิวทัศน์ผาเดียวดาย,ไม่ใช่,1-มิ.ย.,30-ก.ย.,ช่วงฤดูฝนอาจก่อให้เกิดอันตรายได้
12,เขาใหญ่,นครราชสีมา,จุดชมทิวทัศน์ กม.30,ใช่,-,-,-
13,เขาใหญ่,นครนายก,จุดชมทิวทัศน์ผาตรอมใจ (เขาเขียว),ใช่,-,-,-
14,เขาใหญ่,สระบุรี,น้ำตกโกรกอีดก,ใช่,-,-,-
15,เขาใหญ่,นครนายก,เส้นทางศึกษาธรรมชาติศูนย์บริการนักท่องเที่ยว -...,ใช่,-,-,-
16,เขาใหญ่,นครราชสีมา,เส้นทางศึกษาธรรมชาติผากล้วยไม้ - น้ำตกเหวสุวัต,ใช่,-,-,-
17,เขาใหญ่,นครราชสีมา,เส้นทางศึกษาธรรมชาติ กม.33 - หอดูสัตว์หนองผักชี,ใช่,-,-,-
18,เขาใหญ่,นครนายก,เส้นทางศึกษาธรรมชาติดงติ้ว - มอสิงโต,ใช่,-,-,-
19,เขาใหญ่,นครนายก,เส้นทางศึกษาธรรมชาติดงติ้ว - หนองผักชี,ใช่,-,-,-

3. ตรวจความสอดคล้องของสถานะเปิด-ปิด

ตรวจสอบว่าข้อมูลสถานะเปิดตลอดปีและช่วงวันที่ปิดมีความสอดคล้องกัน
ก่อนนำไปสร้างข้อมูล Seasonal Availability ของอุทยาน

In [6]:
print("ไม่เปิดตลอดปี แต่ไม่มีวันที่เริ่มปิด:")
print(
    status[
        (status["เปิดตลอดปี"] == "ไม่ใช่") &
        (status["วันที่เริ่มปิด"].isna())
    ].shape[0]
)

print("\nไม่เปิดตลอดปี แต่ไม่มีวันที่สิ้นสุดการปิด:")
print(
    status[
        (status["เปิดตลอดปี"] == "ไม่ใช่") &
        (status["วันที่สิ้นสุดการปิด"].isna())
    ].shape[0]
)

print("\nเปิดตลอดปี แต่กลับมีวันที่ปิด:")
print(
    status[
        (status["เปิดตลอดปี"] == "ใช่") &
        (
            status["วันที่เริ่มปิด"].notna() |
            status["วันที่สิ้นสุดการปิด"].notna()
        )
    ].shape[0]
)

print("\nตัวอย่างรูปแบบวันที่เริ่มปิด:")
print(
    status["วันที่เริ่มปิด"]
    .dropna()
    .head(15)
    .tolist()
)

print("\nตัวอย่างรูปแบบวันที่สิ้นสุดการปิด:")
print(
    status["วันที่สิ้นสุดการปิด"]
    .dropna()
    .head(15)
    .tolist()
)

ไม่เปิดตลอดปี แต่ไม่มีวันที่เริ่มปิด:
58

ไม่เปิดตลอดปี แต่ไม่มีวันที่สิ้นสุดการปิด:
55

เปิดตลอดปี แต่กลับมีวันที่ปิด:
142

ตัวอย่างรูปแบบวันที่เริ่มปิด:
['1-มี.ค.', '1-มี.ค.', '1-เม.ย.', '-', '-', '-', '-', '-', '-', '-', '-', '1-มิ.ย.', '-', '-', '-']

ตัวอย่างรูปแบบวันที่สิ้นสุดการปิด:
['30-เม.ย.', '30-เม.ย.', '30-เม.ย.', '-', '-', '-', '-', '-', '-', '-', '-', '30-ก.ย.', '-', '-', '-']

In [7]:
print("ตัวอย่างวันที่เริ่มปิด:")
display(
    status.loc[
        status["วันที่เริ่มปิด"].notna(),
        ["วันที่เริ่มปิด", "วันที่สิ้นสุดการปิด"]
    ].head(20)
)

print("\nรูปแบบข้อมูลวันที่เริ่มปิด:")
for value in status["วันที่เริ่มปิด"].dropna().head(20):
    print(repr(value))

ตัวอย่างวันที่เริ่มปิด:

   วันที่เริ่มปิด วันที่สิ้นสุดการปิด
0         1-มี.ค.            30-เม.ย.
1         1-มี.ค.            30-เม.ย.
2         1-เม.ย.            30-เม.ย.
3               -                   -
4               -                   -
5               -                   -
6               -                   -
7               -                   -
8               -                   -
9               -                   -
10              -                   -
11        1-มิ.ย.             30-ก.ย.
12              -                   -
13              -                   -
14              -                   -
15              -                   -
16              -                   -
17              -                   -
18              -                   -
19              -                   -

รูปแบบข้อมูลวันที่เริ่มปิด:
'1-มี.ค.'
'1-มี.ค.'
'1-เม.ย.'
'-'
'-'
'-'
'-'
'-'
'-'
'-'
'-'
'1-มิ.ย.'
'-'
'-'
'-'
'-'
'-'
'-'
'-'
'-'

4. แปลงช่วงเวลาปิดตามฤดูกาล

ปรับข้อมูลช่วงปิดให้อยู่ในรูปแบบวันและเดือน
เพื่อใช้ตรวจว่าแหล่งท่องเที่ยวปิดในช่วงใดของปี
โดยไม่ผูกข้อมูลกับปีใดปีหนึ่ง เนื่องจากเป็นช่วงปิดตามฤดูกาล

In [8]:
import numpy as np
import re

thai_month_map = {
    "ม.ค.": 1,
    "ก.พ.": 2,
    "มี.ค.": 3,
    "เม.ย.": 4,
    "พ.ค.": 5,
    "มิ.ย.": 6,
    "ก.ค.": 7,
    "ส.ค.": 8,
    "ก.ย.": 9,
    "ต.ค.": 10,
    "พ.ย.": 11,
    "ธ.ค.": 12
}

def parse_thai_day_month(value):
    if pd.isna(value):
        return pd.Series([np.nan, np.nan])

    value = str(value).strip()

    # กรณีไม่มีวันที่ระบุ
    if value in ["-", ""]:
        return pd.Series([np.nan, np.nan])

    # เช่น 1-มี.ค.
    match = re.match(r"^(\d{1,2})-(.+)$", value)

    if not match:
        return pd.Series([np.nan, np.nan])

    day = int(match.group(1))
    month_text = match.group(2).strip()

    month = thai_month_map.get(month_text, np.nan)

    return pd.Series([day, month])


status[
    ["close_start_day", "close_start_month"]
] = status["วันที่เริ่มปิด"].apply(parse_thai_day_month)

status[
    ["close_end_day", "close_end_month"]
] = status["วันที่สิ้นสุดการปิด"].apply(parse_thai_day_month)

In [9]:
status[
    [
        "ชื่อหน่วยงาน",
        "ชื่อแหล่งท่องเที่ยว",
        "เปิดตลอดปี",
        "วันที่เริ่มปิด",
        "close_start_day",
        "close_start_month",
        "วันที่สิ้นสุดการปิด",
        "close_end_day",
        "close_end_month"
    ]
].head(20)

,ชื่อหน่วยงาน,ชื่อแหล่งท่องเที่ยว,เปิดตลอดปี,วันที่เริ่มปิด,close_start_day,close_start_month,วันที่สิ้นสุดการปิด,close_end_day,close_end_month
0,เขาใหญ่,แก่งหินเพิง,ไม่ใช่,1-มี.ค.,1.0,3.0,30-เม.ย.,30.0,4.0
1,เขาใหญ่,น้ำตกตะคร้อ,ไม่ใช่,1-มี.ค.,1.0,3.0,30-เม.ย.,30.0,4.0
2,เขาใหญ่,น้ำตกสาริกา,ไม่ใช่,1-เม.ย.,1.0,4.0,30-เม.ย.,30.0,4.0
3,เขาใหญ่,น้ำตกธารทิพย์,ไม่ใช่,-,NaN,NaN,-,NaN,NaN
4,เขาใหญ่,น้ำตกผากล้วยไม้,ใช่,-,NaN,NaN,-,NaN,NaN
5,เขาใหญ่,น้ำตกกองแก้ว,ใช่,-,NaN,NaN,-,NaN,NaN
6,เขาใหญ่,น้ำตกเหวนรก,ใช่,-,NaN,NaN,-,NaN,NaN
7,เขาใหญ่,น้ำตกเหวสุวัต,ใช่,-,NaN,NaN,-,NaN,NaN
8,เขาใหญ่,หอดูสัตว์หนองผักชี,ใช่,-,NaN,NaN,-,NaN,NaN
9,เขาใหญ่,น้ำตกนางรอง,ใช่,-,NaN,NaN,-,NaN,NaN
10,เขาใหญ่,หอดูสัตว์คลองปลากั้ง (ขญ4),ใช่,-,NaN,NaN,-,NaN,NaN
11,เขาใหญ่,จุดชมทิวทัศน์ผาเดียวดาย,ไม่ใช่,1-มิ.ย.,1.0,6.0,30-ก.ย.,30.0,9.0
12,เขาใหญ่,จุดชมทิวทัศน์ กม.30,ใช่,-,NaN,NaN,-,NaN,NaN
13,เขาใหญ่,จุดชมทิวทัศน์ผาตรอมใจ (เขาเขียว),ใช่,-,NaN,NaN,-,NaN,NaN
14,เขาใหญ่,น้ำตกโกรกอีดก,ใช่,-,NaN,NaN,-,NaN,NaN
15,เขาใหญ่,เส้นทางศึกษาธรรมชาติศูนย์บริการนักท่องเที่ยว -...,ใช่,-,NaN,NaN,-,NaN,NaN
16,เขาใหญ่,เส้นทางศึกษาธรรมชาติผากล้วยไม้ - น้ำตกเหวสุวัต,ใช่,-,NaN,NaN,-,NaN,NaN
17,เขาใหญ่,เส้นทางศึกษาธรรมชาติ กม.33 - หอดูสัตว์หนองผักชี,ใช่,-,NaN,NaN,-,NaN,NaN
18,เขาใหญ่,เส้นทางศึกษาธรรมชาติดงติ้ว - มอสิงโต,ใช่,-,NaN,NaN,-,NaN,NaN
19,เขาใหญ่,เส้นทางศึกษาธรรมชาติดงติ้ว - หนองผักชี,ใช่,-,NaN,NaN,-,NaN,NaN

5. ตรวจข้อมูลช่วงปิดที่ไม่สมบูรณ์

ตรวจหารายการที่ระบุว่าไม่ได้เปิดตลอดปี แต่ไม่มีช่วงวันที่ปิด
รวมถึงตรวจรูปแบบวันที่ที่ไม่สามารถแปลงเป็นวันและเดือนได้
ก่อนสร้างสถานะเปิด-ปิดรายเดือน

In [10]:
# 1. ไม่เปิดตลอดปี แต่ไม่มีช่วงวันที่ปิด
missing_close_period = status[
    (status["เปิดตลอดปี"] == "ไม่ใช่") &
    (
        status["close_start_month"].isna() |
        status["close_end_month"].isna()
    )
]

print("ไม่เปิดตลอดปี แต่ช่วงปิดไม่ครบ:")
print(len(missing_close_period))


# 2. มีข้อความวันที่ แต่แปลงไม่ได้
invalid_start = status[
    status["วันที่เริ่มปิด"].notna() &
    (~status["วันที่เริ่มปิด"].isin(["-", ""])) &
    status["close_start_month"].isna()
]

invalid_end = status[
    status["วันที่สิ้นสุดการปิด"].notna() &
    (~status["วันที่สิ้นสุดการปิด"].isin(["-", ""])) &
    status["close_end_month"].isna()
]

print("\nวันที่เริ่มปิดที่แปลงไม่ได้:")
print(len(invalid_start))

print("\nวันที่สิ้นสุดการปิดที่แปลงไม่ได้:")
print(len(invalid_end))


# 3. ดูรายละเอียดของเคสที่ช่วงปิดไม่ครบ
display(
    missing_close_period[
        [
            "ชื่อหน่วยงาน",
            "ชื่อแหล่งท่องเที่ยว",
            "เปิดตลอดปี",
            "วันที่เริ่มปิด",
            "วันที่สิ้นสุดการปิด",
            "สาเหตุการปิด",
            "หมายเหตุ"
        ]
    ].head(30)
)

ไม่เปิดตลอดปี แต่ช่วงปิดไม่ครบ:
72

วันที่เริ่มปิดที่แปลงไม่ได้:
0

วันที่สิ้นสุดการปิดที่แปลงไม่ได้:
5

,ชื่อหน่วยงาน,ชื่อแหล่งท่องเที่ยว,เปิดตลอดปี,วันที่เริ่มปิด,วันที่สิ้นสุดการปิด,สาเหตุการปิด,หมายเหตุ
3,เขาใหญ่,น้ำตกธารทิพย์,ไม่ใช่,-,-,ปิดตลอดทั้งปี,NaN
27,เขาใหญ่,ลานกางเต็นท์ผากล้วยไม้,ไม่ใช่,-,-,ปิดตลอดทั้งปี,NaN
46,ปางสีดา,ภูเขาเจดีย์,ไม่ใช่,-,-,NaN,NaN
49,ปางสีดา,ทุ่งหญ้าบุตาปอด,ไม่ใช่,-,-,ปิดตลอดทั้งปี,NaN
53,ปางสีดา,จุดสกัดลานหิน,ไม่ใช่,NaN,NaN,ปิดตลอดทั้งปี,NaN
54,ปางสีดา,ลานหินดาด,ไม่ใช่,-,-,ปิดตลอดทั้งปี,NaN
100,หมู่เกาะช้าง,เกาะเทียน,ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN
101,หมู่เกาะช้าง,เกาะกระ,ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN
102,หมู่เกาะช้าง,เกาะทองหลาง,ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN
131,เขาชะเมา-เขาวง,บ้านโซนที่ 3 โซนหน่วยพิทักษ์อุทยานแห่งชาติ (คล...,ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN
155,เขื่อนศรีนครินทร์,บ้านโซนที่ 5 โซนหน่วยพิทักษ์อุทยานแห่งชาติ (น้...,ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN
173,ไทรโยค,บ้านพักโซนที่ 1 โซนที่ทำการอุทยานแห่งชาติ บริเ...,ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN
259,เขาสามร้อยยอด,ลานกางเต็นท์ทุ่งสามร้อยยอด,ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN
301,เขาสก,น้ำตกสิบเอ็ดชั้น,ไม่ใช่,NaN,NaN,ปิดตลอดปี,NaN
309,เขาสก,บัวผุด หน่วย ฯ บางหมาน,ไม่ใช่,NaN,NaN,ปิดตลอดปี,NaN
335,หมู่เกาะชุมพร,บ้านโซนที่ 1 โซนที่ทำการอุทยานแห่งชาติบนฝั่ง บ...,ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN
361,ใต้ร่มเย็น,บ้านโซนที่ 1 โซนที่ทำการอุทยานแห่งชาติ,ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN
369,น้ำตกหงาว,บ้านโซน 1 (ที่ทำการอุทยานแห่งชาติ),ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN
370,น้ำตกหงาว,ลานกางเต็นท์อุทยานแห่งชาติน้ำตกหงาว,ไม่ใช่,NaN,NaN,NaN,NaN
378,คลองพนม,ภาพเขียนสี (เพิงเขานกยาง),ไม่ใช่,NaN,ไม่มีกำหนด,กำลังพัฒนาเส้นทางและสิ่งอำนวยความสะดวก,NaN
383,คลองพนม,ถ้ำพระ,ไม่ใช่,NaN,ไม่มีกำหนด,กำลังพัฒนาเส้นทางและสิ่งอำนวยความสะดวก,NaN
385,คลองพนม,เส้นทางชมบัวผุดบ้านถ้ำผึ้ง,ไม่ใช่,NaN,ไม่มีกำหนด,ฟื้นฟูทรัพยากร,ฟื้นฟูทรัพยากร
392,ลำน้ำกระบุรี,บ้านโซนที่ 1 โซนที่ทำการอุทยานแห่งชาติ อยู่บนฝ...,ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN
430,หาดนพรัตน์ธารา-หมู่เกาะพีพี,เกาะยูง,ไม่ใช่,NaN,NaN,ฟื้นฟูทรัพยากร,ปิดไม่มีกำหนด
477,หมู่เกาะสิมิลัน,เกาะตาชัย (พื้นที่บนเกาะ ชายหาด และแนวปะการังร...,ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด (ตั้งแต่วันที่ 15 ต.ค. 2559 เป็น...,NaN
478,หมู่เกาะสิมิลัน,กองหินแฟนตาซี (Fantasy Reef),ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN
479,หมู่เกาะสิมิลัน,อ่าวไฟแว๊บ,ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN
480,หมู่เกาะสิมิลัน,อ่าวงวงช้าง,ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN
483,หมู่เกาะสิมิลัน,เรือนกล้วยไม้ เกาะปายู (เกาะเจ็ด),ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN
484,หมู่เกาะสิมิลัน,หินม้วนเดียว (เกาะห้า-เกาะหก),ไม่ใช่,NaN,NaN,ปิดไม่มีกำหนด,NaN

6. สร้างสถานะเปิด-ปิดรายเดือน

แปลงข้อมูลช่วงปิดตามฤดูกาลให้อยู่ในรูปแบบรายเดือน
โดยกำหนดสถานะเป็น Open, Closed หรือ Unknown
เพื่อเตรียมนำไปสรุปเป็นระดับอุทยาน

In [11]:
def get_month_status(row, month):
    
    # เปิดตลอดปี
    if row["เปิดตลอดปี"] == "ใช่":
        return "Open"
    
    start_month = row["close_start_month"]
    end_month = row["close_end_month"]
    
    # ไม่เปิดตลอดปี แต่ไม่มีข้อมูลช่วงปิด
    if pd.isna(start_month) or pd.isna(end_month):
        return "Unknown"
    
    start_month = int(start_month)
    end_month = int(end_month)
    
    # ช่วงปิดอยู่ภายในปีเดียวกัน
    # เช่น มิ.ย. - ก.ย.
    if start_month <= end_month:
        if start_month <= month <= end_month:
            return "Closed"
        return "Open"
    
    # ช่วงปิดข้ามปี
    # เช่น พ.ย. - ก.พ.
    else:
        if month >= start_month or month <= end_month:
            return "Closed"
        return "Open"

In [12]:
monthly_status_rows = []

for _, row in status.iterrows():
    
    for month in range(1, 13):
        
        monthly_status_rows.append({
            "park_name": row["ชื่อหน่วยงาน"],
            "attraction_name": row["ชื่อแหล่งท่องเที่ยว"],
            "province": row["จังหวัด"],
            "latitude": row["latitude"],
            "longitude": row["longitude"],
            "month": month,
            "status": get_month_status(row, month)
        })

attraction_monthly_status = pd.DataFrame(monthly_status_rows)

attraction_monthly_status.head(20)

   park_name attraction_name    province  latitude  longitude  month  status
0    เขาใหญ่     แก่งหินเพิง  ปราจีนบุรี  14.16748  101.72896      1    Open
1    เขาใหญ่     แก่งหินเพิง  ปราจีนบุรี  14.16748  101.72896      2    Open
2    เขาใหญ่     แก่งหินเพิง  ปราจีนบุรี  14.16748  101.72896      3  Closed
3    เขาใหญ่     แก่งหินเพิง  ปราจีนบุรี  14.16748  101.72896      4  Closed
4    เขาใหญ่     แก่งหินเพิง  ปราจีนบุรี  14.16748  101.72896      5    Open
5    เขาใหญ่     แก่งหินเพิง  ปราจีนบุรี  14.16748  101.72896      6    Open
6    เขาใหญ่     แก่งหินเพิง  ปราจีนบุรี  14.16748  101.72896      7    Open
7    เขาใหญ่     แก่งหินเพิง  ปราจีนบุรี  14.16748  101.72896      8    Open
8    เขาใหญ่     แก่งหินเพิง  ปราจีนบุรี  14.16748  101.72896      9    Open
9    เขาใหญ่     แก่งหินเพิง  ปราจีนบุรี  14.16748  101.72896     10    Open
10   เขาใหญ่     แก่งหินเพิง  ปราจีนบุรี  14.16748  101.72896     11    Open
11   เขาใหญ่     แก่งหินเพิง  ปราจีนบุรี  14.16748  101.72896     12    Open
12   เขาใหญ่     น้ำตกตะคร้อ  ปราจีนบุรี  14.18198  101.59266      1    Open
13   เขาใหญ่     น้ำตกตะคร้อ  ปราจีนบุรี  14.18198  101.59266      2    Open
14   เขาใหญ่     น้ำตกตะคร้อ  ปราจีนบุรี  14.18198  101.59266      3  Closed
15   เขาใหญ่     น้ำตกตะคร้อ  ปราจีนบุรี  14.18198  101.59266      4  Closed
16   เขาใหญ่     น้ำตกตะคร้อ  ปราจีนบุรี  14.18198  101.59266      5    Open
17   เขาใหญ่     น้ำตกตะคร้อ  ปราจีนบุรี  14.18198  101.59266      6    Open
18   เขาใหญ่     น้ำตกตะคร้อ  ปราจีนบุรี  14.18198  101.59266      7    Open
19   เขาใหญ่     น้ำตกตะคร้อ  ปราจีนบุรี  14.18198  101.59266      8    Open

7. สรุปสถานะเปิด-ปิดระดับอุทยาน

รวมสถานะของแหล่งท่องเที่ยวภายในแต่ละอุทยานเป็นรายเดือน
เพื่อดูจำนวนจุดที่เปิด ปิด หรือไม่มีข้อมูล และคำนวณสัดส่วนความพร้อม
สำหรับการท่องเที่ยวในแต่ละเดือน

In [13]:
park_month_availability = (
    attraction_monthly_status
    .groupby(["park_name", "month"])
    .agg(
        total_attractions=("attraction_name", "count"),
        open_attractions=("status", lambda x: (x == "Open").sum()),
        closed_attractions=("status", lambda x: (x == "Closed").sum()),
        unknown_attractions=("status", lambda x: (x == "Unknown").sum())
    )
    .reset_index()
)

# จำนวนจุดที่เรารู้สถานะจริง
park_month_availability["known_attractions"] = (
    park_month_availability["open_attractions"] +
    park_month_availability["closed_attractions"]
)

# % จุดที่เปิด จากเฉพาะจุดที่ทราบสถานะ
park_month_availability["availability_pct"] = (
    park_month_availability["open_attractions"]
    / park_month_availability["known_attractions"]
    * 100
)

# % ข้อมูลที่ยังไม่ทราบสถานะ
park_month_availability["unknown_pct"] = (
    park_month_availability["unknown_attractions"]
    / park_month_availability["total_attractions"]
    * 100
)

park_month_availability.head(20)

,park_name,month,total_attractions,open_attractions,closed_attractions,unknown_attractions,known_attractions,availability_pct,unknown_pct
0,กุยบุรี,1,2,2,0,0,2,100.0,0.0
1,กุยบุรี,2,2,2,0,0,2,100.0,0.0
2,กุยบุรี,3,2,2,0,0,2,100.0,0.0
3,กุยบุรี,4,2,2,0,0,2,100.0,0.0
4,กุยบุรี,5,2,2,0,0,2,100.0,0.0
5,กุยบุรี,6,2,2,0,0,2,100.0,0.0
6,กุยบุรี,7,2,2,0,0,2,100.0,0.0
7,กุยบุรี,8,2,2,0,0,2,100.0,0.0
8,กุยบุรี,9,2,2,0,0,2,100.0,0.0
9,กุยบุรี,10,2,2,0,0,2,100.0,0.0
10,กุยบุรี,11,2,2,0,0,2,100.0,0.0
11,กุยบุรี,12,2,2,0,0,2,100.0,0.0
12,ขุนขาน,1,4,4,0,0,4,100.0,0.0
13,ขุนขาน,2,4,4,0,0,4,100.0,0.0
14,ขุนขาน,3,4,4,0,0,4,100.0,0.0
15,ขุนขาน,4,4,4,0,0,4,100.0,0.0
16,ขุนขาน,5,4,4,0,0,4,100.0,0.0
17,ขุนขาน,6,4,4,0,0,4,100.0,0.0
18,ขุนขาน,7,4,4,0,0,4,100.0,0.0
19,ขุนขาน,8,4,3,1,0,4,75.0,0.0

 8. ตรวจและบันทึกข้อมูล Availability ระดับอุทยาน

ตรวจ Missing Values ข้อมูลซ้ำ และช่วงค่าของ Availability
ก่อนบันทึกเป็น Clean Dataset สำหรับเชื่อมกับข้อมูลนักท่องเที่ยวและสภาพอากาศ

In [14]:
print("ขนาดข้อมูล:")
print(park_month_availability.shape)

print("\nMissing Values:")
print(park_month_availability.isna().sum())

print("\nข้อมูลซ้ำ อุทยาน + เดือน:")
print(
    park_month_availability.duplicated(
        subset=["park_name", "month"]
    ).sum()
)

print("\nช่วง Availability:")
print(
    park_month_availability["availability_pct"].min(),
    "-",
    park_month_availability["availability_pct"].max()
)

print("\nจำนวนอุทยาน:")
print(park_month_availability["park_name"].nunique())

ขนาดข้อมูล:
(2940, 9)

Missing Values:
park_name               0
month                   0
total_attractions       0
open_attractions        0
closed_attractions      0
unknown_attractions     0
known_attractions       0
availability_pct       24
unknown_pct            24
dtype: int64

ข้อมูลซ้ำ อุทยาน + เดือน:
0

ช่วง Availability:
0.0 - 100.0

จำนวนอุทยาน:
245

9. กรองข้อมูล Availability ให้ตรงกับอุทยานในชุด Tourism

เลือกเฉพาะอุทยานที่มีอยู่ในชุดข้อมูลนักท่องเที่ยว
เพื่อไม่ให้วนอุทยานหรือหน่วยงานอื่นปะปนในการวิเคราะห์

In [15]:
# โหลดรายชื่ออุทยานที่ใช้ใน Tourism
tourism = pd.read_csv(
    "../data/processed/tourism_clean.csv"
)

tourism_parks = set(
    tourism["park_name"].dropna().unique()
)

print("จำนวนอุทยานใน Tourism:")
print(len(tourism_parks))

print("\nจำนวนหน่วยงานใน Availability ก่อนกรอง:")
print(status["ชื่อหน่วยงาน"].nunique())

จำนวนอุทยานใน Tourism:
165

จำนวนหน่วยงานใน Availability ก่อนกรอง:
245

In [16]:
status_national = status[
    status["ชื่อหน่วยงาน"].isin(tourism_parks)
].copy()

print("จำนวนอุทยานที่จับคู่ได้:")
print(status_national["ชื่อหน่วยงาน"].nunique())

unmatched_status_parks = sorted(
    set(tourism_parks) -
    set(status_national["ชื่อหน่วยงาน"].unique())
)

print("\nจำนวนอุทยาน Tourism ที่ยังหาไม่เจอในข้อมูลเปิด-ปิด:")
print(len(unmatched_status_parks))

print("\nรายชื่อ:")
print(unmatched_status_parks)

จำนวนอุทยานที่จับคู่ได้:
153

จำนวนอุทยาน Tourism ที่ยังหาไม่เจอในข้อมูลเปิด-ปิด:
12

รายชื่อ:
['ดอยสอยมาลัย', 'ต้นสักใหญ่ (คลองตรอน)', 'ถ้ำปลา-น้ำตกผาเสื่อ', 'ผาแดง (เชียงดาว)', 'ภูผายา', 'ภูผาเทิบ (มุกดาหาร)', 'ภูสระดอกบัว', 'ภูสวนทราย (นาแห้ว)', 'เขาคิชฌกูฎ', 'แก่งเจ็ดแคว', 'แม่ยวมฝั่งซ้าย', 'ไม้กลายเป็นหิน']

10. ปรับรูปแบบชื่ออุทยานก่อนเชื่อมข้อมูลเปิด-ปิด

ปรับชื่ออุทยานจากข้อมูลนักท่องเที่ยวและข้อมูลเปิด-ปิด
ให้อยู่ในรูปแบบมาตรฐานเดียวกัน เพื่อลดปัญหาจากช่องว่าง
เครื่องหมายขีด คำนำหน้า และสถานะเตรียมการ

In [17]:
import re

def normalize_park_name(name):
    if pd.isna(name):
        return None

    name = str(name).strip()

    # ทำ Unicode ให้เป็นรูปแบบเดียวกัน
    name = pd.Series([name]).str.normalize("NFC").iloc[0]

    # ลบคำว่า "อุทยานแห่งชาติ" หน้าชื่อ ถ้ามี
    name = re.sub(r"^อุทยานแห่งชาติ\s*", "", name)

    # ลบสถานะเตรียมการ
    name = re.sub(r"\s*\(เตรียมการฯ?\)", "", name)

    # ลบช่องว่างล่องหน
    name = name.replace("\u200b", "")

    # จัดเครื่องหมายขีดให้เหมือนกัน
    name = re.sub(r"\s*[-–—]\s*", "-", name)

    # ช่องว่างหลายตัวให้เหลือหนึ่ง
    name = re.sub(r"\s+", " ", name)

    return name.strip()


tourism["park_status_key"] = (
    tourism["park_name"]
    .apply(normalize_park_name)
)

status["park_status_key"] = (
    status["ชื่อหน่วยงาน"]
    .apply(normalize_park_name)
)


matched_after_clean = set(tourism["park_status_key"]) & set(status["park_status_key"])

unmatched_after_clean = sorted(
    set(tourism["park_status_key"]) -
    set(status["park_status_key"])
)

print("จำนวนอุทยานที่จับคู่ได้หลังปรับชื่อ:")
print(len(matched_after_clean))

print("\nจำนวนที่ยังจับคู่ไม่ได้:")
print(len(unmatched_after_clean))

print("\nรายชื่อ:")
print(unmatched_after_clean)

จำนวนอุทยานที่จับคู่ได้หลังปรับชื่อ:
153

จำนวนที่ยังจับคู่ไม่ได้:
12

รายชื่อ:
['ดอยสอยมาลัย', 'ต้นสักใหญ่ (คลองตรอน)', 'ถ้ำปลา-น้ำตกผาเสื่อ', 'ผาแดง (เชียงดาว)', 'ภูผายา', 'ภูผาเทิบ (มุกดาหาร)', 'ภูสระดอกบัว', 'ภูสวนทราย (นาแห้ว)', 'เขาคิชฌกูฎ', 'แก่งเจ็ดแคว', 'แม่ยวมฝั่งซ้าย', 'ไม้กลายเป็นหิน']

11. ตรวจชื่ออุทยานที่ยังจับคู่ไม่ได้

ค้นหาชื่อในข้อมูลเปิด-ปิดที่มีความใกล้เคียงกับอุทยานที่ยังจับคู่ไม่ได้
เพื่อใช้ตรวจสอบชื่อเก่า ชื่อใหม่ หรือรูปแบบการเรียกที่แตกต่างกัน
ก่อนกำหนด Mapping แบบเจาะจง

In [18]:
from difflib import SequenceMatcher

status_park_names = (
    status["park_status_key"]
    .dropna()
    .unique()
)

match_results = []

for name in unmatched_after_clean:

    best_match = None
    best_score = 0

    for candidate in status_park_names:

        score = SequenceMatcher(
            None,
            name,
            candidate
        ).ratio()

        if score > best_score:
            best_score = score
            best_match = candidate

    match_results.append({
        "tourism_name": name,
        "closest_status_name": best_match,
        "similarity": round(best_score, 2)
    })

status_name_matches = pd.DataFrame(match_results)

status_name_matches.sort_values(
    "similarity",
    ascending=False
)

             tourism_name         closest_status_name  similarity
8              เขาคิชฌกูฎ                  เขาคิชฌกูฏ        0.90
2     ถ้ำปลา-น้ำตกผาเสื่อ              ถ้ำปลา-ผาเสื่อ        0.85
6             ภูสระดอกบัว                    ภูสระบัว        0.84
4                  ภูผายา                      ภูผายล        0.83
11         ไม้กลายเป็นหิน  ดอยสอยมาลัย-ไม้กลายเป็นหิน        0.70
7      ภูสวนทราย (นาแห้ว)                   ภูสวนทราย        0.67
1   ต้นสักใหญ่ (คลองตรอน)                  ต้นสักใหญ่        0.65
0             ดอยสอยมาลัย  ดอยสอยมาลัย-ไม้กลายเป็นหิน        0.59
5     ภูผาเทิบ (มุกดาหาร)                    ภูผาเทิบ        0.59
10         แม่ยวมฝั่งซ้าย                       แม่ยม        0.53
3        ผาแดง (เชียงดาว)                       ผาแดง        0.48
9             แก่งเจ็ดแคว                  แก่งกระจาน        0.48

12. กำหนด Mapping สำหรับชื่ออุทยานที่ตรวจสอบแล้ว

ปรับชื่อเฉพาะกรณีที่สามารถระบุได้ว่าเป็นอุทยานเดียวกัน
โดยไม่ใช้ Fuzzy Matching รวมชื่อโดยอัตโนมัติ
เพื่อป้องกันการเชื่อมข้อมูลผิดระหว่างอุทยานคนละแห่ง

In [25]:
# Mapping เฉพาะชื่อที่ตรวจสอบแล้ว
status_mapping = {
    "ถ้ำปลา-น้ำตกผาเสื่อ": "ถ้ำปลา-ผาเสื่อ",
    "ไม้กลายเป็นหิน": "ดอยสอยมาลัย-ไม้กลายเป็นหิน",
    "ภูสวนทราย (นาแห้ว)": "ภูสวนทราย",
    "ต้นสักใหญ่ (คลองตรอน)": "ต้นสักใหญ่",
    "ดอยสอยมาลัย": "ดอยสอยมาลัย-ไม้กลายเป็นหิน",
    "ภูผาเทิบ (มุกดาหาร)": "ภูผาเทิบ",
    "ผาแดง (เชียงดาว)": "ผาแดง"
}

In [26]:
khao_khitchakut_match = (
    status_name_matches
    .loc[
        status_name_matches["tourism_name"] == "เขาคิชฌกูฎ",
        "closest_status_name"
    ]
    .iloc[0]
)

status_mapping["เขาคิชฌกูฎ"] = khao_khitchakut_match

In [27]:
tourism["park_status_final"] = (
    tourism["park_status_key"]
    .replace(status_mapping)
)

In [28]:
remaining_status_unmatched = sorted(
    set(tourism["park_status_final"]) -
    set(status["park_status_key"])
)

print("จำนวนที่ยังจับคู่ไม่ได้:")
print(len(remaining_status_unmatched))

print("\nรายชื่อ:")
print(remaining_status_unmatched)

จำนวนที่ยังจับคู่ไม่ได้:
4

รายชื่อ:
['ภูผายา', 'ภูสระดอกบัว', 'แก่งเจ็ดแคว', 'แม่ยวมฝั่งซ้าย']

13. ตรวจชื่อปัจจุบันของอุทยานที่ยังจับคู่ไม่ได้

ค้นหาชื่ออุทยานที่เกี่ยวข้องกับชื่อเก่าหรือชื่อที่เปลี่ยนแปลง
ในชุดข้อมูลเปิด-ปิด ก่อนกำหนด Mapping ขั้นสุดท้าย

In [29]:
search_terms = [
    "ภูสระ",
    "ภูหินจอมธาตุ",
    "ภูพระบาท",
    "แควน้อย",
    "แม่เงา",
    "แม่ยวม"
]

for term in search_terms:
    matches = sorted(
        status.loc[
            status["park_status_key"].str.contains(
                term,
                na=False,
                regex=False
            ),
            "park_status_key"
        ].unique()
    )

    print(f"\nค้นหา: {term}")
    print(matches)

ค้นหา: ภูสระ
['ภูสระบัว']

ค้นหา: ภูหินจอมธาตุ
['ภูหินจอมธาตุ-ภูพระบาท']

ค้นหา: ภูพระบาท
['ภูหินจอมธาตุ-ภูพระบาท']

ค้นหา: แควน้อย
['แควน้อย']

ค้นหา: แม่เงา
['แม่เงา']

ค้นหา: แม่ยวม
['น้ำตกแม่ยวมหลวง']

## 14. กำหนด Mapping ขั้นสุดท้ายสำหรับชื่ออุทยาน

กำหนดชื่อมาตรฐานสำหรับอุทยานที่ตรวจสอบความสัมพันธ์ของชื่อเก่าและชื่อปัจจุบันแล้ว
และไม่บังคับจับคู่กรณีที่ยังมีความไม่แน่นอน

In [30]:
final_status_mapping = {
    "ภูสระดอกบัว": "ภูสระบัว",
    "ภูผายา": "ภูหินจอมธาตุ-ภูพระบาท",
    "แก่งเจ็ดแคว": "แควน้อย"
}

tourism["park_status_final"] = (
    tourism["park_status_final"]
    .replace(final_status_mapping)
)

remaining_status_unmatched = sorted(
    set(tourism["park_status_final"]) -
    set(status["park_status_key"])
)

print("จำนวนที่ยังจับคู่ไม่ได้:")
print(len(remaining_status_unmatched))

print("\nรายชื่อ:")
print(remaining_status_unmatched)

จำนวนที่ยังจับคู่ไม่ได้:
1

รายชื่อ:
['แม่ยวมฝั่งซ้าย']

15. สร้าง Availability Dataset ขั้นสุดท้าย

สร้างข้อมูลสถานะการเปิด-ปิดรายเดือนสำหรับอุทยานทั้งหมดในชุดข้อมูลนักท่องเที่ยว
โดยเชื่อมกับข้อมูลเปิด-ปิดที่ตรวจสอบชื่อแล้ว และเก็บกรณีที่ไม่มีข้อมูลยืนยัน
เป็น Unknown แทนการสมมติว่าเปิดหรือปิด

In [32]:
import numpy as np

# สร้างสถานะรายเดือนจากข้อมูลเปิด-ปิดใหม่
availability_rows = []

for _, row in status.iterrows():

    for month in range(1, 13):

        availability_rows.append({
            "park_status_key": row["park_status_key"],
            "attraction_name": row["ชื่อแหล่งท่องเที่ยว"],
            "month": month,
            "status": get_month_status(row, month)
        })

status_monthly = pd.DataFrame(availability_rows)


# สรุปจากระดับแหล่งท่องเที่ยว -> ระดับอุทยาน
status_park_month = (
    status_monthly
    .groupby(["park_status_key", "month"])
    .agg(
        total_attractions=("attraction_name", "count"),
        open_attractions=("status", lambda x: (x == "Open").sum()),
        closed_attractions=("status", lambda x: (x == "Closed").sum()),
        unknown_attractions=("status", lambda x: (x == "Unknown").sum())
    )
    .reset_index()
)

status_park_month["known_attractions"] = (
    status_park_month["open_attractions"]
    + status_park_month["closed_attractions"]
)

status_park_month["availability_pct"] = (
    status_park_month["open_attractions"]
    / status_park_month["known_attractions"]
    * 100
)

status_park_month["unknown_pct"] = (
    status_park_month["unknown_attractions"]
    / status_park_month["total_attractions"]
    * 100
)

In [33]:
# รายชื่ออุทยาน 165 แห่งของ Tourism
tourism_park_map = (
    tourism[
        ["park_name", "park_status_final"]
    ]
    .drop_duplicates()
)

# เดือน 1-12
months = pd.DataFrame({
    "month": range(1, 13)
})

# 165 อุทยาน × 12 เดือน
park_month_base = tourism_park_map.merge(
    months,
    how="cross"
)

# เชื่อมกับ Availability
park_availability_final = park_month_base.merge(
    status_park_month,
    left_on=["park_status_final", "month"],
    right_on=["park_status_key", "month"],
    how="left"
)

# ระบุว่ามีข้อมูล Availability หรือไม่
park_availability_final["availability_data_status"] = np.where(
    park_availability_final["availability_pct"].notna(),
    "Known",
    "Unknown"
)

In [34]:
print("ขนาดข้อมูล:")
print(park_availability_final.shape)

print("\nจำนวนอุทยาน:")
print(park_availability_final["park_name"].nunique())

print("\nจำนวนเดือน:")
print(park_availability_final["month"].nunique())

display(
    park_availability_final[
        park_availability_final["park_name"] == "แม่ยวมฝั่งซ้าย"
    ]
)

ขนาดข้อมูล:
(1980, 12)

จำนวนอุทยาน:
165

จำนวนเดือน:
12

,park_name,park_status_final,month,park_status_key,total_attractions,open_attractions,closed_attractions,unknown_attractions,known_attractions,availability_pct,unknown_pct,availability_data_status
1872,แม่ยวมฝั่งซ้าย,แม่ยวมฝั่งซ้าย,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown
1873,แม่ยวมฝั่งซ้าย,แม่ยวมฝั่งซ้าย,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown
1874,แม่ยวมฝั่งซ้าย,แม่ยวมฝั่งซ้าย,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown
1875,แม่ยวมฝั่งซ้าย,แม่ยวมฝั่งซ้าย,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown
1876,แม่ยวมฝั่งซ้าย,แม่ยวมฝั่งซ้าย,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown
1877,แม่ยวมฝั่งซ้าย,แม่ยวมฝั่งซ้าย,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown
1878,แม่ยวมฝั่งซ้าย,แม่ยวมฝั่งซ้าย,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown
1879,แม่ยวมฝั่งซ้าย,แม่ยวมฝั่งซ้าย,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown
1880,แม่ยวมฝั่งซ้าย,แม่ยวมฝั่งซ้าย,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown
1881,แม่ยวมฝั่งซ้าย,แม่ยวมฝั่งซ้าย,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown
1882,แม่ยวมฝั่งซ้าย,แม่ยวมฝั่งซ้าย,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown
1883,แม่ยวมฝั่งซ้าย,แม่ยวมฝั่งซ้าย,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown

 16. บันทึก Availability Clean Dataset

บันทึกข้อมูลสถานะเปิด-ปิดรายเดือนระดับอุทยาน
โดยเก็บกรณีที่ไม่มีข้อมูลยืนยันเป็น Unknown
เพื่อใช้เชื่อมกับข้อมูลนักท่องเที่ยวและปริมาณฝน

In [35]:
from pathlib import Path

processed_dir = Path("../data/processed")

park_availability_final.to_csv(
    processed_dir / "park_availability_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

print("บันทึก park_availability_clean.csv เรียบร้อย")
print(park_availability_final.shape)

บันทึก park_availability_clean.csv เรียบร้อย
(1980, 12)